# Generated by Django 5.1 on 2024-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('players', models.JSONField(default=list)),
                ('matches', models.JSONField(default=list)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
